[package]
name = "burn-rust"
version = "0.1.0"
edition = "2024"
license = "AGPL-3"
description = "a simple POSIX/UNIX cli tool to burn .iso images to a disk."

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
gpt = "4.1.0"

[[bin]]
name = "burn"
path = "src/main.rs"
